### ISSUE TITLE
cpanm is indexed with wrong distribution/release

### ISSUE THREAD

**Issue by tsibley** [metacpan/metacpan-api#373]
https://metacpan.org/pod/cpanm brings you to Metabrik, not App::cpanminus.

The API reports at http://api.metacpan.org/v0/module/cpanm?fields=name,documentation,release,path,authorized

```
{
   "path" : "bin/metabrik-cpanm",
   "release" : "Metabrik-1.03",
   "name" : "metabrik-cpanm",
   "documentation" : "cpanm",
   "authorized" : "true"
}
```

It seems like a file shouldn't be marked authorized if the documentation value doesn't match something in 06perms?

**Comment by rwstauner** [comment]
The behavior of of the pod shortcut for anything not listed in 02packages is undefined (so you're not supposed to use https://metacpan.org/pod/cpanm).
If you go to the release page for either dist you'll see it linking to a longer (dist-specific) url.

App-cpanminus looks to have made a more recent release and is now the winner.

That said, you bring up a long-standing issue (there are several) in that the nature of `"indexed"` and `"authorized"` are not well defined/understood/agreed upon.

The documentation for ["indexed"](https://github.com/CPAN-API/cpan-api/blob/master/lib/MetaCPAN/Document/File.pm#L281-L286)
says "include in the search index", however that sounds different to me than the more verbose documentation for ["set_indexed"](https://github.com/CPAN-API/cpan-api/blob/master/lib/MetaCPAN/Document/File.pm#L686-L704).
It was once described to me that "indexed" essentially meant "not `no_index`ed by the META file"
and that seems like roughly what "set_indexed" is doing.

The "authorized" value defaults to true and gets set to false *if* the module is in 06perms but the releaser is *not* associated with it.

So by those definitions both of these "cpanm" files from each dist would get marked true/true.
That's obviously not very helpful, though, because in this case,
while neither is explicitly *not* indexed (by META), nor *not* authorized (by 06perms),
they are also not *actually* indexed (in 02packages) nor *actually* authorized (in 06perms)...
So I'm still not sure what the right answer is.
If the pod files were indexed:false and authorized:false they wouldn't be searchable on the web site.

I'd love to come up with a clearer definition for these values.
If we can come up with better attributes we could put it in the next version of the API.

**Comment by ranguard** [comment]
Closing in favour of #323 which references this
