### ISSUE TITLE
Add a flag to author to indicate that an author has passed away

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-api#620]
There was a suggestion that we should memorialize CPAN author pages.  In order to do this, the API needs to know about the deceased.  

There are two possible data sources:

`authors/00whois.xml`  In this file, the information is in the fullname key.  eg "<fullname>Nick Ing-Simmons (PAUSE Custodial Account)</fullname>"

There is also `Acme::CPANAuthors::InMemoriam` but it looks to lag behind `00whois.xml`.

@andk are there any cases of custodial accounts for authors who are still living or is this explicitly a way to flag an author as deceased?

**Comment by mickeyn** [comment]
Maybe we shouldn't trust automation around this. but create a flag (in the authors type) that we only update manually upon request (and verification)?

**Comment by oalders** [comment]
Are you saying not to trust automation because there might be some kind of typo in the custodial designation that would cause us to skip that author?  I believe that if it's flagged on the PAUSE side it has already gone through some kind of verification.

On the other hand, I guess anybody could update their full name to include that text.  That would be a weird edge case.

**Comment by mickeyn** [comment]
i had 2 things in mind:
1. it doesn't (hopefully) happen often enough to deserve coding/maintenance.
2. it's a sensitive topic and we may not want any mistakes be made by code bugs.

the PAUSE verification is indeed all the verification we need, but we can monitor it for changes and just report them for manual updates rather than automatic.

that said, I don't have a strong objection here, just sharing the first things that came to mind.

**Comment by andk** [comment]
>>>>> On Wed, 08 Mar 2017 10:51:49 -0800, Olaf Alders <notifications@github.com> said:

  > @andk are there any cases of custodial accounts for authors who are
  > still living or is this explicitly a way to flag an author as
  > deceased?

The practice of adding " (PAUSE Custodial Account)" has evolved circa 10
years ago and seems to have been applied consistently since ~2010. I
think it is reasonable to trust this. There are archives of
modules@perl.org to study who changed what when in case of doubt, but I
personally have no doubt. Thanks to those who cared so well for the
data.

-- 
andreas

**Comment by shadowcat-mst** [comment]
@mickeyn it might not happen that often, but it's Not F-ing Fun and anything that makes the process easier would be gratefully received - after contacting pause and scouring for nickserv accounts to lock on magnet and freenode I'm generally Very Done with dealing it and just want to go get a drink.

**Comment by oalders** [comment]
@mickeyn is this working?  I don't see a custodial flag on https://fastapi.metacpan.org/v1/author/KHAMPTON

**Comment by mickeyn** [comment]
hmm... we have several such accounts already marked, not sure yet what happened in this case.
investigating.

**Comment by mickeyn** [comment]
it works on my VM but i don't see an author script running as cron
will poke @ranguard on IRC

**Comment by ranguard** [comment]
@mickeyn 

https://github.com/metacpan/metacpan-api/blob/master/bin/cron/author.sh

on lw-mc-03 is:

`0 * * * * /home/metacpan/metacpan-api/bin/cron/author.sh`

**Comment by mickeyn** [comment]
thanks, found it yesterday.
#626 fixed the last sub-issue (https://fastapi.metacpan.org/v1/author/KHAMPTON).

@oalders can we close this one?

**Comment by oalders** [comment]
Thanks @mickeyn!
