### ISSUE TITLE
download_url endpoint is missing `version` on certain modules (e.g. Math::BigInt )

### ISSUE THREAD

**Issue by ribasushi** [metacpan/metacpan-api#787]
Note - while the ticket is centered around `Math::BigInt` this is likely a wider problem within the metacpan index.

At the time of filing the `download_url` endpoint of [Math::BigInt](https://fastapi.metacpan.org/v1/download_url/Math::BigInt) does not return a `"version" :` component unlike most modules ( e.g. [Math::BigRat](https://fastapi.metacpan.org/v1/download_url/Math::BigRat) )

This cascades through multiple layers culminating in `cpanm`'s inability to upgrade `Math::BigInt` if the `--dev` option is used: https://travis-ci.org/ribasushi/travis-mathbigint-wtf/jobs/345591614#L475-L476 ( `perl 5.26` ships with `1.999806`, current on CPAN is `1.999811` ).

Many thanks to @haarg for the initial diagnosis and identifying the likely culprit: [a `package`-change not followed by a `$VERSION` within one of the files](https://metacpan.org/source/PJACKLAM/Math-BigInt-1.999811/lib/Math/BigInt/CalcEmu.pm#L9)

@miyagawa: mentioning you on this ticket, as if the metacpan fix is difficult/delayed, it may make sense to patch-up `cpanm` to treat a missing version as "not installed at all"

**Comment by haarg** [comment]
This should be fixed by 6a6f90f4a12830800c46bb3793d32f3bdb058cbf.

The code was attempting to sort based on module versions.  There can be multiple modules per file, and the sort filter wasn't properly being applied.  Rather than sort by a module matching the given name, it was sorting by any of the module versions.  This could still get confused if a dist had a given package listed multiple times with different versions, but that should be rare enough to not be a significant issue.
