### ISSUE TITLE
How to use the scroll API to get all the module's name?

### ISSUE THREAD

**Issue by newthis** [metacpan/metacpan-api#788]
Hi, I want to know how to fetch all the metapan's module's name, it seems that only 5000 results can be fetched via by the search API. Is there some way to get the whole moduel's list?

**Comment by oalders** [comment]
Here's an example of how to do this for releases: https://github.com/metacpan/metacpan-examples/blob/master/scripts/release/7-all-releases.pl  You should be able to do something similar for modules.

**Comment by newthis** [comment]
Still confused, is there other examples or API , I am not quite familar with Perl. 
How to achieve this in other languages ?

**Comment by mickeyn** [comment]
This is basically Elasticsearch (2.4), so you can use their HTTP API to scroll search.
Check out [Scroll](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-scroll.html) documentation.

To help you further - please specify what you mean by 'all modules' names' ... as I'm not really sure that's what you're after since `modules` are subsets of `releases` (`release = distribution + version`).
Can you please provide more details about your use-case?

**Comment by mickeyn** [comment]
closing. please re-open if still an issue we can help with.
