### ISSUE TITLE
river ranking doesn't consider test prereqs

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-api#843]
Test-Inline is listed at '1 bar' for the CPAN river: https://metacpan.org/release/Test-Inline

However it is depended upon by Moose (as a test prereq), which has 4 bars: https://metacpan.org/release/Moose

shouldn't Test-Inline also be ranked with 4 bars?

**Comment by oalders** [comment]
@neilb this is by design, correct? @jberger does your river implementation follow the same logic?

**Comment by neilb** [comment]
Test prereqs are included, it's development prereqs that aren't included.

The phases included are: `qw/ configure runtime build test /`.

Is MetaCPAN using Joel's implementation now?

**Comment by oalders** [comment]
> Is MetaCPAN using Joel's implementation now?

No, I don't think so.

**Comment by neilb** [comment]
In that case, I'll look into what's going on with Test-Inline

**Comment by neilb** [comment]
`Test::Inline` appears twice in `META.json` for Moose. Here's a cut-down extract:

      "develop" : {
         "requires" : {
            ...
            "Test::Inline" : "0",
            ...
         },
         "suggests" : {
            ...
            "Test::Inline" : "0",
            ...
         }
      },

So it's listed as a **develop**ment prereq, rather than a **test** one. As noted above, development prereqs aren't included in the river calculation.

To be included in the river calculation it would have to be in **test**.**requires** (not **suggests**, as they're ignored as well).

**Comment by oalders** [comment]
Thanks @karenetheridge and @neilb. Let me know if we need to re-open this.
